# Generated by Django 2.2.16 on 2020-09-23 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login', models.CharField(max_length=50, verbose_name='Имя')),
                ('text', models.TextField(verbose_name='Текст')),
            ],
        ),
        migrations.DeleteModel(
            name='Users',
        ),
    ]
